apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vsiup879c-java-quarkus 
  janus-idp.io/tekton: vsiup879c-java-quarkus
  backstage.io/kubernetes-id: vsiup879c-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vsiup879c-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml